//! Dates
//! Dates in JavaScript are represented by the Date object, which provides a way to work with dates and times. The Date object can be created using the new Date() constructor, which can take various arguments to specify the date and time. Once a Date object is created, you can use various methods to manipulate and format the date and time.

let myDate = new Date(); // This creates a new Date object with the current date and time. The Date object has various methods to get and set the date and time, as well as to format the date and time in different ways.
console.log(myDate.toString()); // This method returns a string representation of the date and time in a human-readable format. The output will depend on the locale and time zone settings of the environment where the code is running. For example, it might return something like "Sat Jan 14 2023 12:00:00 GMT+0000 (Coordinated Universal Time)". The exact format may vary based on the implementation of JavaScript and the environment, but it generally includes the day of the week, month, day of the month, year, time, and time zone information.
console.log(myDate.toDateString()); // This method returns a string representation of the date portion of the Date object, without the time. The output will typically include the day of the week, month, day of the month, and year. For example, it might return something like "Sat Jan 14 2023". The exact format may vary based on the implementation of JavaScript and the environment, but it generally includes the day of the week, month, day of the month, and year.
console.log(myDate.toTimeString()); // This method returns a string representation of the time portion of the Date object, without the date. The output will typically include the hours, minutes, seconds, and time zone information. For example, it might return something like "12:00:00 GMT+0000 (Coordinated Universal Time)". The exact format may vary based on the implementation of JavaScript and the environment, but it generally includes the hours, minutes, seconds, and time zone information.
console.log(myDate.toLocaleString()); // This method returns a string representation of the date and time in a locale-specific format. The output will depend on the locale settings of the environment where the code is running.
console.log(typeof myDate); // The typeof operator returns "object" for Date objects, as they are a type of object in JavaScript. The Date object is a built-in object that provides methods for working with dates and times, and it is considered an object type in JavaScript. Therefore, when you use typeof on a Date object, it will return "object".

// let myCreatedDate = new Date(2023, 0, 23) //! This creates a new Date object representing January 23, 2023. The month is zero-indexed, so 0 corresponds to January, 1 to February, and so on. The day of the month is specified as the third argument. The resulting Date object will represent the date and time corresponding to January 23, 2023 at 00:00:00 (midnight) in the local time zone of the environment where the code is running.
// let myCreatedDate = new Date("2023-01-14") //! This creates a new Date object representing January 14, 2023. The date string is in the format "YYYY-MM-DD", which is a common format for representing dates. The resulting Date object will represent the date and time corresponding to January 14, 2023 at 00:00:00 (midnight) in the local time zone of the environment where the code is running.
// let myCreatedDate = new Date("01-14-2023") //! This creates a new Date object representing January 14, 2023. The date string is in the format "MM-DD-YYYY", which is another common format for representing dates. The resulting Date object will represent the date and time corresponding to January 14, 2023 at 00:00:00 (midnight) in the local time zone of the environment where the code is running.
// let myCreatedDate = new Date(2023, 0, 23, 5, 3) //! This creates a new Date object representing January 23, 2023 at 05:03:00. The month is zero-indexed, so 0 corresponds to January, 1 to February, and so on. The day of the month is specified as the third argument, and the hours and minutes are specified as the fourth and fifth arguments, respectively. The resulting Date object will represent the date and time corresponding to January 23, 2023 at 05:03:00 in the local time zone of the environment where the code is running.
// let myCreatedDate = new Date("2023-01-14") //! This creates a new Date object representing January 14, 2023. The date string is in the format "YYYY-MM-DD", which is a common format for representing dates. The resulting Date object will represent the date and time corresponding to January 14, 2023 at 00:00:00 (midnight) in the local time zone of the environment where the code is running.
// let myCreatedDate = new Date("01-14-2023"); //! This creates a new Date object representing January 14, 2023. The date string is in the format "MM-DD-YYYY", which is another common format for representing dates. The resulting Date object will represent the date and time corresponding to January 14, 2023 at 00:00:00 (midnight) in the local time zone of the environment where the code is running.
// console.log(myCreatedDate.toLocaleString()); //! This method returns a string representation of the date and time in a locale-specific format. The output will depend on the locale settings of the environment where the code is running. For example, it might return something like "1/14/2023, 12:00:00 AM" in the United States locale, or "14/01/2023, 00:00:00" in the United Kingdom locale. The exact format may vary based on the implementation of JavaScript and the environment, but it generally includes the date and time in a format that is appropriate for the specified locale.

let myTimeStamp = Date.now(); //! This method returns the number of milliseconds elapsed since January 1, 1970 00:00:00 UTC (Coordinated Universal Time). This value is often referred to as a "timestamp" and is commonly used for measuring time intervals or for storing date and time information in a compact format. The value returned by Date.now() is a large integer representing the number of milliseconds since the epoch (January 1, 1970), and it can be used to create Date objects or to perform calculations with dates and times.

// console.log(myTimeStamp); //! The output will be a large integer representing the number of milliseconds since January 1, 1970 00:00:00 UTC. For example, it might return something like 1673740800000, which corresponds to January 14, 2023 at 00:00:00 UTC. The exact value will depend on the current date and time when the code is executed, as well as the time zone settings of the environment where the code is running.
// console.log(myCreatedDate.getTime()); //! This method returns the number of milliseconds since January 1, 1970 00:00:00 UTC for the specified Date object. It is similar to Date.now(), but it returns the timestamp for the specific date and time represented by the Date object. For example, if myCreatedDate represents January 14, 2023 at 00:00:00, then myCreatedDate.getTime() will return a large integer representing the number of milliseconds since January 1, 1970 00:00:00 UTC for that specific date and time. The exact value will depend on the date and time represented by the Date object, as well as the time zone settings of the environment where the code is running.
// console.log(Math.floor(Date.now()/1000)); //! This code snippet calculates the current timestamp in seconds by dividing the number of milliseconds returned by Date.now() by 1000 and then using Math.floor() to round down to the nearest whole number. The output will be a large integer representing the number of seconds since January 1, 1970 00:00:00 UTC. For example, it might return something like 1673740800, which corresponds to January 14, 2023 at 00:00:00 UTC. The exact value will depend on the current date and time when the code is executed, as well as the time zone settings of the environment where the code is running.

let newDate = new Date(); //! This creates a new Date object with the current date and time. The Date object has various methods to get and set the date and time, as well as to format the date and time in different ways. The resulting Date object will represent the current date and time in the local time zone of the environment where the code is running.
console.log(newDate); //! The output will be a string representation of the current date and time in a human-readable format. The exact format may vary based on the implementation of JavaScript and the environment, but it generally includes the day of the week, month, day of the month, year, time, and time zone information. For example, it might return something like "Sat Jan 14 2023 12:00:00 GMT+0000 (Coordinated Universal Time)". The output will depend on the locale and time zone settings of the environment where the code is running.

console.log(newDate.getFullYear()); //! This method returns the year of the specified Date object as a four-digit number. For example, if newDate represents January 14, 2023, then newDate.getFullYear() will return 2023. The output will depend on the date represented by the Date object, as well as the time zone settings of the environment where the code is running.
console.log(newDate.getMonth() + 1); //! This method returns the month of the specified Date object as a zero-indexed value (0 for January, 1 for February, and so on). To get the month in a more human-readable format (1 for January, 2 for February, etc.), you can add 1 to the result. For example, if newDate represents January 14, 2023, then newDate.getMonth() will return 0, and newDate.getMonth() + 1 will return 1. The output will depend on the date represented by the Date object, as well as the time zone settings of the environment where the code is running.
console.log(newDate.getDate()); //! This method returns the day of the month for the specified Date object as a number between 1 and 31. For example, if newDate represents January 14, 2023, then newDate.getDate() will return 14. The output will depend on the date represented by the Date object, as well as the time zone settings of the environment where the code is running.
console.log(newDate.getDay()); //! This method returns the day of the week for the specified Date object as a zero-indexed value (0 for Sunday, 1 for Monday, and so on). For example, if newDate represents January 14, 2023, then newDate.getDay() will return 6 (Saturday). The output will depend on the date represented by the Date object, as well as the time zone settings of the environment where the code is running.

// `${newDate.getDay()} and the time ` //! This code snippet uses template literals to create a string that includes the day of the week (as a zero-indexed value) and the time. The output will depend on the date represented by the Date object, as well as the time zone settings of the environment where the code is running. For example, if newDate represents January 14, 2023 at 12:00:00, then `${newDate.getDay()} and the time` will return "6 and the time", since newDate.getDay() will return 6 (Saturday). The exact output may vary based on the implementation of JavaScript and the environment, but it will generally include the day of the week and some representation of the time.

newDate.toLocaleString("default", {
  weekday: "long",
});
// This code snippet uses the toLocaleString() method to format the date and time according to the specified locale and options. The "default" locale will use the default locale settings of the environment where the code is running. The options object specifies that the weekday should be displayed in its long form (e.g., "Monday", "Tuesday", etc.). The output will depend on the date represented by the Date object, as well as the locale settings of the environment. For example, if newDate represents January 14, 2023, then newDate.toLocaleString("default", { weekday: "long" }) will return "Saturday". The exact output may vary based on the implementation of JavaScript and the environment, but it will generally include the day of the week in its long form.